### ISSUE TITLE
Link to the actual SubAccount Role Collection Name

### ISSUE THREAD

**Issue by torrobswe** [SAP-samples/teched2024-XP280#41]
hi
In Excercise3 https://github.com/SAP-samples/teched2024-XP280/tree/main/exercises/ex3 
we add the modules and also the code to add my email address into the Target RoleCollections.

Where in the scripts is the link between what we give as input parameters in variables.tf and the result:

module.build_code.btp_subaccount_role_collection_assignment.**app_studio_developer**["myemail@mail.com"]: 
Creation complete after 1s [id=c3b45791-a8d9-4cd8-a2ef-cc21574ee978,**Business_Application_Studio_Developer**,myemail@mail.com]

**Comment by lechnerc77** [comment]
I am not sure if I understand the question correctly, but trying a first answer here:

The module encapsulates the setup of  [build code](https://github.com/SAP-samples/teched2024-XP280/tree/main/modules/build_code) in a reusable manner so that the caller does not have to care about the details of this setup. In analogy to a method or a function the module has some input parameters defined in the `variables.tf` and output that is defined by the module as outputs. The mechanism is the same that you used in the `outputs.tf`. The calling module (in your case the root module `main.tf`) does not have direct access to any data inside of the module except for the data that is surfaced via outputs. 

In this exercise the module contains the assignment of the role collection using the input you provided via the values you handed into the module defined by the module's [variables](https://github.com/SAP-samples/teched2024-XP280/blob/main/modules/build_code/build_code_variables.tf).  The [output](https://github.com/SAP-samples/teched2024-XP280/blob/main/modules/build_code/build_code_outputs.tf) of the module does not contain any information about the role collection assignment and nothing is surfaced to the root module/`main.tf`

Terraform *per se* of course sees what is in the module and also displays the execution steps and used resources in the Terminal output as well as in the Terraform state. When you inspect the state via `terraform show` or `terraform state list` and then `terraform state show ...` for the resource you want to take a closer look at, you will find this information too.

Hope that answers your question

**Comment by lechnerc77** [comment]
Here the flow in more detail:

In the variables.tf file you specify the input parameters for the configuration that you crafted in the main.tf file. In your case the email addresses of the persons that should become the admins of BAS. The name of the parameter is completely up to you.
You define the values for this input parameter in the terraform.tfvars file.
 
Looking at the main.tf you will see that this variables is handed over to a module (https://github.com/SAP-samples/teched2024-XP280/blob/main/solutions/ex4/main.tf#L22):
 
![image](https://github.com/user-attachments/assets/7d901bda-0f06-4430-af9a-2ad65bb1fb3e)
 
The module represents a reusable asset in Terraform that usually bundles the configuration to several resources that logically belong together. The “source” parameter tells you where Terraform fetches the code of the module; in our case it is locally in the directory “modules” on root level (https://github.com/SAP-samples/teched2024-XP280/tree/main/modules/build_code).
 
![image](https://github.com/user-attachments/assets/54948a66-9b78-46ae-8781-dd04d2870558)

The “build_code_variables.tf” file defines the input variable “application_studio_admins” where we passed the value in the screenshot from above. This value is used in the configuration defined in the  “build_code.tf” file. The assignment that you are looking for happens in line 101 (https://github.com/SAP-samples/teched2024-XP280/blob/main/modules/build_code/build_code.tf#L101)
 
![image](https://github.com/user-attachments/assets/e130fc87-6a63-4776-9679-7c641f5f8800)

We advise Terraform to iterate over the list of values in “var.application_studio_admin” via the “for_each” in line 102. Every entry gets assigned to the role collection with the name in line 104 namely “Business_Application_Studio_Administrator”.
